version: '3.4'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.2.0
    container_name: broker
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
      - "9094:9094"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_INTERNAL://broker:29092, OUTSIDE://localhost:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  auth:
    image: auth
    build:
      context: .
      dockerfile: ./Dockerfile.auth
    depends_on:
      - broker

  camera:
    image: camera
    build:
      context: .
      dockerfile: ./Dockerfile.camera
    depends_on:
      - broker

  connector:
    image: connector
    build:
      context: .
      dockerfile: ./Dockerfile.connector
    depends_on:
      - broker

  fly_control:
    image: fly_control
    build:
      context: .
      dockerfile: ./Dockerfile.fly_control
    depends_on:
      - broker

  hw_control:
    image: hw_control
    build:
      context: .
      dockerfile: ./Dockerfile.hw_control
    depends_on:
      - broker

  lidar:
    image: lidar
    build:
      context: .
      dockerfile: ./Dockerfile.lidar
    depends_on:
      - broker

  navigate_glonas:
    image: navigate_glonas
    build:
      context: .
      dockerfile: ./Dockerfile.navigate_glonas
    depends_on:
      - broker

  navigate_inertional:
    image: navigate_inertional
    build:
      context: .
      dockerfile: ./Dockerfile.navigate_inertional
    depends_on:
      - broker

  navigate_gps:
    image: navigate_gps
    build:
      context: .
      dockerfile: ./Dockerfile.navigate_gps
    depends_on:
      - broker

  sprayer:
    image: sprayer
    build:
      context: .
      dockerfile: ./Dockerfile.sprayer
    depends_on:
      - broker

  monitor:
    image: monitor
    build:
      context: .
      dockerfile: ./Dockerfile.monitor
    volumes:
      - ./storage/:/storage
    depends_on:
      - broker
