FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY navgate_glonas /navgate_glonas
COPY config.ini /navgate_glonas/

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /navgate_glonas
USER appuser

WORKDIR /navgate_glonas
CMD ["python", "navgate_glonas.py", "config.ini"]
