FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY hw_control /hw_control
COPY config.ini /hw_control/

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /hw_control
USER appuser

WORKDIR /hw_control
CMD ["python", "hw_control.py", "config.ini"]
