FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY navgate_inertional /navgate_inertional
COPY config.ini /navgate_inertional/

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /navgate_inertional
USER appuser

WORKDIR /navgate_inertional
CMD ["python", "navgate_inertional.py", "config.ini"]
