FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY navigate_gps /navigate_gps
COPY config.ini /navigate_gps/

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /navigate_gps
USER appuser

WORKDIR /navigate_gps
CMD ["python", "navigate_gps.py", "config.ini"]
