FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY camera /camera
COPY config.ini /camera/

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /camera
USER appuser

WORKDIR /camera
CMD ["python", "camera.py", "config.ini"]
