FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY auth /auth
COPY config.ini /auth/

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /auth
USER appuser

WORKDIR /auth
CMD ["python", "auth.py", "config.ini"]
