FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY lidar /lidar
COPY config.ini /lidar/

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /lidar
USER appuser

WORKDIR /lidar
CMD ["python", "lidar.py", "config.ini"]
