FROM python:3.8-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY navigate_inertional /navigate_inertional
COPY config.ini /navigate_inertional/

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /navigate_inertional
USER appuser

WORKDIR /navigate_inertional
CMD ["python", "navigate_inertional.py", "config.ini"]
